containerPort: 3111
image:
  pullPolicy: IfNotPresent
  repository: agwcolor/techtrends
  tag: latest
livenessProbe: /healthz
namespace:
  name: sandbox
readinessProbe: /healthz
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 256Mi
service:
  port: 4111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP
